import { GTMState } from './types';

/**
 * Generate a text summary of the GTM report for export
 */
export function generateReportText(state: GTMState): string {
  const lines: string[] = [];

  lines.push('═══════════════════════════════════════');
  lines.push('       GTM STRATEGY REPORT');
  lines.push('       Generated by GTM.quest');
  lines.push('═══════════════════════════════════════');
  lines.push('');

  // Company Info
  if (state.company_name || state.industry) {
    lines.push('COMPANY PROFILE');
    lines.push('───────────────────────────────────────');
    if (state.company_name) lines.push(`Company: ${state.company_name}`);
    if (state.industry) lines.push(`Industry: ${state.industry}`);
    if (state.stage) lines.push(`Stage: ${state.stage}`);
    if (state.target_market) lines.push(`Target Market: ${state.target_market}`);
    if (state.budget) lines.push(`Budget: $${state.budget.toLocaleString()}/mo`);
    lines.push('');
  }

  // Strategy
  if (state.strategy) {
    lines.push('RECOMMENDED STRATEGY');
    lines.push('───────────────────────────────────────');
    lines.push(`Strategy: ${state.strategy.name}`);
    lines.push(`Type: ${state.strategy.type.toUpperCase()}`);
    lines.push('');
    lines.push(state.strategy.summary);
    lines.push('');

    if (state.strategy.action_items.length > 0) {
      lines.push('Action Items:');
      state.strategy.action_items.forEach((item, i) => {
        lines.push(`  ${i + 1}. ${item}`);
      });
      lines.push('');
    }
  }

  // ROI Projection
  if (state.roi_projection) {
    lines.push('ROI PROJECTION');
    lines.push('───────────────────────────────────────');
    lines.push(`Estimated CAC: $${state.roi_projection.estimated_cac.toLocaleString()}`);
    lines.push(`Estimated LTV: $${state.roi_projection.estimated_ltv.toLocaleString()}`);
    lines.push(`LTV:CAC Ratio: ${(state.roi_projection.estimated_ltv / state.roi_projection.estimated_cac).toFixed(1)}x`);
    lines.push(`Payback Period: ${state.roi_projection.payback_months} months`);
    lines.push(`Confidence: ${state.roi_projection.confidence}`);
    if (state.roi_projection.notes) {
      lines.push('');
      lines.push(`Notes: ${state.roi_projection.notes}`);
    }
    lines.push('');
  }

  // Recommended Agencies
  if (state.recommended_providers && state.recommended_providers.length > 0) {
    lines.push('RECOMMENDED AGENCIES');
    lines.push('───────────────────────────────────────');
    state.recommended_providers.forEach((provider, i) => {
      lines.push(`${i + 1}. ${provider.name}`);
      if (provider.match_score) {
        lines.push(`   Match Score: ${Math.round(provider.match_score * 100)}%`);
      }
      if (provider.description) {
        lines.push(`   ${provider.description}`);
      }
      if (provider.website) {
        lines.push(`   Website: ${provider.website}`);
      }
      lines.push('');
    });
  }

  // Timeline
  if (state.timeline_phases && state.timeline_phases.length > 0) {
    lines.push('IMPLEMENTATION TIMELINE');
    lines.push('───────────────────────────────────────');
    state.timeline_phases.forEach((phase) => {
      lines.push(`${phase.name} (${phase.duration})`);
      phase.activities.forEach((activity) => {
        lines.push(`  • ${activity}`);
      });
      if (phase.milestones.length > 0) {
        lines.push('  Milestones:');
        phase.milestones.forEach((milestone) => {
          lines.push(`    ◆ ${milestone}`);
        });
      }
      lines.push('');
    });
  }

  // Budget Breakdown
  if (state.budget_breakdown) {
    lines.push('BUDGET ALLOCATION');
    lines.push('───────────────────────────────────────');
    lines.push(`Total: $${state.budget_breakdown.total.toLocaleString()}/mo`);
    lines.push('');
    state.budget_breakdown.categories.forEach((cat) => {
      lines.push(`  ${cat.name}: $${cat.amount.toLocaleString()} (${cat.percentage}%)`);
    });
    lines.push('');
  }

  lines.push('═══════════════════════════════════════');
  lines.push('Generated by GTM.quest - https://gtm.quest');
  lines.push(`Date: ${new Date().toLocaleDateString()}`);
  lines.push('═══════════════════════════════════════');

  return lines.join('\n');
}

/**
 * Download report as text file
 */
export function downloadReport(state: GTMState) {
  const text = generateReportText(state);
  const blob = new Blob([text], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `gtm-strategy-${state.company_name?.toLowerCase().replace(/\s+/g, '-') || 'report'}-${new Date().toISOString().split('T')[0]}.txt`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

/**
 * Copy report to clipboard
 */
export async function copyReportToClipboard(state: GTMState): Promise<boolean> {
  try {
    const text = generateReportText(state);
    await navigator.clipboard.writeText(text);
    return true;
  } catch {
    return false;
  }
}
